language: java
jdk: openjdk11
os: linux
dist: xenial
services:
- docker
cache:
  timeout: 180
  directories:
  - "$HOME/.m2/repository"
install:
- mvn install -U -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
- if [[ "$TRAVIS_BRANCH" =~ master* ]]; then mvn test -B -P release; fi
- if ! [[ "$TRAVIS_BRANCH" =~ master* ]]; then mvn test -B; fi
before_deploy:
- if [[ "$TRAVIS_BRANCH" =~ master* ]]; then echo $GPG_SECRET_KEYS | base64 --decode
  | $GPG_EXECUTABLE --import; fi
- if [[ "$TRAVIS_BRANCH" =~ master* ]]; then echo $GPG_OWNERTRUST | base64 --decode
  | $GPG_EXECUTABLE --import-ownertrust; fi
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
deploy:
- provider: script
  script: cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy -DskipTests=true
    && docker build . -t contentgroup/cqf-ruler:develop && docker push contentgroup/cqf-ruler:develop
  cleanup: false
  skip_cleanup: true
  on:
    branch: develop
- provider: script
  script: cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy -P release
    -DskipTests=true  && docker build . -t contentgroup/cqf-ruler && docker push contentgroup/cqf-ruler
  cleanup: false
  skip_cleanup: true
  on:
    branch: master
before_cache:
- rm -rf $HOME/.m2/repository/org/opencds/cqf/parent
- rm -rf $HOME/.m2/repository/org/opencds/cqf/common
- rm -rf $HOME/.m2/repository/org/opencds/cqf/dstu3
- rm -rf $HOME/.m2/repository/org/opencds/cqf/r4
- rm -rf $HOME/.m2/repository/org/opencds/cqf/cqf-ruler-dstu3
- rm -rf $HOME/.m2/repository/org/opencds/cqf/cqf-ruler-r4
notifications:
  slack:
    rooms:
      secure: UcwCk/9xDrkLXtaHPXJAsJuyZN7MIzRunndBpxMk/fwiAF56ZscPMu5IlPN72x2TqdkDPDAykGnczQ/w76txFcIzyH9/06fmXh//8XL/YWpERsfCW9q1XOn+xTTXwrxF5f6eaAMqYlNDe5tXLCOHCEnuHpdFNnFoNasZ2dTqaDNP+jjPLlSO0zhVv5zW4d75lpklg2+SQra5smgKW4eXJO6z4mXFJtkhN/lKwlgKCKbC+G8o3QO+zSJouyeCmr6xdPkTob1va8jNuR1SRIlk943btmZAUlfLh9pUMO2Hhay1BJhXpFrO5ZE3eCwU9jaoCyoTTPcVBytOKKNbGr1miRM/fDdxDYUMGQbqmkKDMqTZzkeLSbQPH92bs2lUILZf0xr2wbi8mZICdz0HZwRkaLzF6okIeQ69/b7/QNbDXAxKlT0DaShtidVbUfwNb/mUOXc3fkjn8vShPn7n9xtdLQvrGR9bJVHHBIDYS+dge2EtdPzsrmHsEhGS153uytPgF+zcYwRN83Xpyjk78+AMQFmzorErz6I+74ZQyXFzN4Z2Z1SfeGGpBp7uUK7dDD1WYVk370hf5oU19euWdSWmzBDajrLlalH25VKt140lQBMU6QyDmdraWM0f0iut034QbTUisOo+O2Km0AhZdTVTVmZSyLOJ6Ec+lusU2AHtayM=
